// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Employees__CardIdController from "./employees/card_id_controller"
application.register("employees--card-id", Employees__CardIdController)
