require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "app/assets/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "public/**/*"
    - "vendor/**/*"
    - "db/migrate/*"

Style/Documentation:
  Enabled: false
